### ISSUE TITLE
HTML driver

### ISSUE THREAD

**Issue by TylorS** [motorcyclejs/motorcycle#4]
Moving the conversation from https://github.com/motorcyclejs/dom/issues/12
here as an HTML driver should be separate from the DOM driver.
# Overview

An HTML driver would allow for server-side rendering for SEO purposes and increased speed on initial render.
# References

https://github.com/acstll/snabbdom-to-html

**Comment by Frikki** [comment]
I think it is a good idea to have the HTML driver separated. It looks like that repo completely would solve this. The question is if there’s anything in that repo which we _don’t_ need?

**Comment by TylorS** [comment]
Good question, the nice thing about it is it's modular similar to snabbdom. So it could be used as

``` js
makeHTMLDriver([
  require('snabbdom-to-html/module/attributes'),
  require('snabbdom-to-html/module/style'),
])
```

to pick and choose what _is_ needed just as is offered with the DOM driver.

**Comment by Frikki** [comment]
Huh? So the user should be responsible for requiring modules from _snabbdom-to-html_? I don’t think that’s a good idea.

**Comment by TylorS** [comment]
I agree, it would come with a set of sensible defaults.And the user can optionally choose to include more or less. That's how it's done with the DOM driver.

``` js
makeDOMDriver(container, modules = [
  require('snabbdom/modules/class'),
  require('snabbdom/modules/attributes'),
  require('snabbdom/modules/props'),
  require('snabbdom/modules/style'),
])
```

So if it's not provided it still continues to work. But as it stands with `snabbdom-to-html` I would think that both of the modules offered would almost always be needed to be remotely useful. The optional parameters could be forgone until there are possibly more modules that would warrant that behavior.

**Comment by Frikki** [comment]
Okay.

**Comment by TylorS** [comment]
https://github.com/motorcyclejs/html
